run:
  timeout: 5m
  tests: true
  build-tags:
    - sqlite_omit_load_extension

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  goconst:
    min-len: 3
    min-occurrences: 3
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: triggermesh
  
  govet:
    enable:
      - shadow
  
  gosec:
    severity: medium
    confidence: medium
  
  misspell:
    locale: US
  
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: if-return
        severity: warning
        disabled: false
      - name: increment-decrement
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false

linters:
  enable:
    - errcheck
    - goconst
    - gofmt
    - goimports
    - revive
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
  disable:
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - gocritic
    - gocyclo
    - err113
    - noctx
    - nolintlint
    - rowserrcheck
    - stylecheck
    - testpackage
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-dirs:
    - bin
    - data
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 10

